spring:
  application:
    name: spring-ai-mcp
  ai:
    mcp:
      client:
        enabled: true
        type: SYNC
#        sse:
#          connections:
#            brave:
#              url: http://localhost:8000
#              sse-endpoint: /sse
    anthropic:
      api-key: ${ANTHROPIC_API_KEY}
      chat:
        options:
          model: claude-sonnet-4-6
