spring:
  ai:
    mcp:
      client:
        enabled: true
        type: SYNC
        http:
          connections:
            fetch:
              url: http://mcpo:8000/fetch/mcp
              headers:
                Authorization: "Bearer top-secret"
            brave-search:
              url: http://mcpo:8000/brave-search/mcp
              headers:
                Authorization: "Bearer top-secret"
    anthropic:
      api-key: ${ANTHROPIC_API_KEY}
      chat:
        options:
          model: claude-sonnet-4-6
