spring:
  application:
    name: spring-ai-mcp
  ai:
    mcp:
      client:
        enabled: true
        type: SYNC
        sse:
          connections:
            mcp-fetch:
              url: http://mcp-proxy-custom:8000
              sse-endpoint: /servers/fetch/sse
            mcp-brave-search:
              url: http://mcp-proxy-custom:8000
              sse-endpoint: /servers/brave-search/sse
    anthropic:
      api-key: ${ANTHROPIC_API_KEY}
      chat:
        options:
          model: claude-sonnet-4-6
