spring:
  application:
    name: spring-ai-mcp
  ai:
    mcp:
      client:
        enabled: true
        type: SYNC
        sse:
          connections:
            mcp-brave-search:
              url: http://mcp-brave-search:8000
              sse-endpoint: /sse
            mcp-github:
              url: http://mcp-github:8001
              sse-endpoint: /sse
    anthropic:
      api-key: ${ANTHROPIC_API_KEY}
      chat:
        options:
          model: claude-sonnet-4-6
